### PR TITLE
adding the whois server for .cloud domains

### PR DESCRIPTION
**Pull request by linuxjuggler**

### CODE REVIEW

**Comment by linuxjuggler** [comment]
Sadly this is going to provide very limited information about the domain, a better whois server can be whois.namecheap.com and the same server can be for `.name` domains

**Comment by hjr265** [comment]
@linuxjuggler We can use that as the default. Would you like to update the merge request with it and the entry for ".name"?

**Comment by linuxjuggler** [comment]
@hjr265 done.

**Comment by hjr265** [comment]
Thank you, @linuxjuggler!

**Pull request merged**
