### PR TITLE
PR: to fix issues with whois.yesnic.com

### PR DESCRIPTION
**Pull request by zbone3**
The lookup on domain `eigene.io` (with `follow:2`) caused a `BAD_PORT` error on node socket lib that was uncatchable and made the entire app crash. It seems this error is not catchable on socket.on('error').

After an initial investigation, I found that the issue rooted from the server that was returned as `http:/whois.yesnic.com` instead of just `whois.yesnic.com`, after following the initial whois server. This caused the code, that splits on `:` to interpret `http` as the server and `/whois.yesnic.com` as the port which caused the error.

I added additional parsing logic to `cleanParsingErrors` and validation that the port is indeed a number and not a string, with a fallback to port 43

Additional:
- Added test to ensure this produces a catchable error (socket.on('error')) 
- Added  support for new mocha lib (v8+), that caused tests to fail due to deprecation of `--compilers`  flag on mocha test

### CODE REVIEW

**Comment by zbone3** [comment]
@hjr265 Could you please have a quick look and let me know if this could be merged?
Thanks

**Comment by hjr265** [comment]
@zbone3 Looks like there is a small issue in the new test code:

```
Furqan Software/node-whois [zbone3-master●] » make test
./node_modules/.bin/mocha -u bdd -R spec -t 10000 -s 5000 --require coffeescript/register test.coffee

/home/hjr265/Furqan Software/node-whois/test.coffee:168:3: error: indentation mismatch
  it 'should avoid socket BAD_PORT Error and fail with a catchable ECONNRESET with whois.yesnic.com (eigene.io)', (done) ->
  ^
make: *** [Makefile:13: test] Error 1
```

Can you please push a fix for this?

**Comment by zbone3** [comment]
@hjr265 Apologies for that. My indentation didn't match the project's - fixed that.
Added rebuild script, for clean install and tested that the test passes.
Removed older coffee-script package

**Comment by zbone3** [comment]
@hjr265 kind reminder

**Pull request merged**
